CREATE TABLE `bbscs_agreeagainst` (
  `ID` varchar(40) NOT NULL default '',
  `UserID` varchar(40) NOT NULL default '',
  `PostID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `VoteType` tinyint(1) default '0',
  `CreateTime` bigint(20) NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `id` (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_board` (
  `ID` bigint(20) NOT NULL auto_increment,
  `ParentID` bigint(20) NOT NULL default '0',
  `ParentIDs` varchar(255) default NULL,
  `ChildIDs` varchar(255) default NULL,
  `BoardName` varchar(60) NOT NULL default '',
  `Explains` text,
  `Bulletin` text,
  `BoardPic` varchar(200) default NULL,
  `UseStat` tinyint(1) default '1',
  `Orders` int(11) default '0',
  `NeedPasswd` tinyint(1) default '0',
  `Passwd` varchar(100) default NULL,
  `BoardLevel` int(11) default '0',
  `BoardType` tinyint(3) default '0',
  `AllowHTML` tinyint(1) default '0',
  `AllowUBB` tinyint(1) default '0',
  `AuditPost` tinyint(1) default '0',
  `AuditAttach` tinyint(1) default '0',
  `AddUserPostNum` tinyint(1) default '1',
  `IsHidden` tinyint(1) default '0',
  `IsAuth` tinyint(1) default '0',
  `MainPostNum` int(11) default '0',
  `PostNum` int(11) default '0',
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_boardauthuser` (
  `ID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `UserID` varchar(40) NOT NULL default '',
  `UserName` varchar(20) NOT NULL default '',
  `CreateTime` bigint(20) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_boardmaster` (
  `ID` bigint(20) NOT NULL auto_increment,
  `BoardID` bigint(20) NOT NULL default '0',
  `UserName` varchar(20) NOT NULL default '',
  `Purview` varchar(200) default NULL,
  `RoleID` int(11) default '0',
  `OverChildPurview` tinyint(3) default '0',
  `IsHidden` tinyint(3) default '0',
  PRIMARY KEY  (`ID`),
  KEY `BoardID` (`BoardID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_boardpermission` (
  `ID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `GroupID` int(11) NOT NULL default '0',
  `Permissions` text,
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `BoardID_GroupID` (`BoardID`,`GroupID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_boardsave` (
  `ID` varchar(40) NOT NULL default '',
  `UserID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  UNIQUE KEY `UserID` (`UserID`,`BoardID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_boardtag` (
  `ID` varchar(40) NOT NULL,
  `BoardID` bigint(20) NOT NULL,
  `TagName` varchar(255) NOT NULL,
  `Orders` int(11) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_bookmark` (
  `ID` varchar(40) NOT NULL default '',
  `UserID` varchar(40) NOT NULL default '',
  `BookMarkName` varchar(255) NOT NULL default '',
  `Url` varchar(255) default NULL,
  `Alt` varchar(255) default NULL,
  `IsShare` tinyint(1) default '1',
  `CreateTime` datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `UserID` (`UserID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_choice` (
  `ID` varchar(40) NOT NULL default '',
  `CategoryID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `BoardName` varchar(60) NOT NULL default '',
  `PostID` varchar(40) NOT NULL default '',
  `PostMainID` varchar(40) NOT NULL default '',
  `UserID` varchar(40) NOT NULL default '',
  `UserName` varchar(20) NOT NULL default '',
  `UserNickName` varchar(60) default NULL,
  `Title` varchar(150) default NULL,
  `CreateTime` bigint(20) default NULL,
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_choicecategory` (
  `ID` varchar(40) NOT NULL default '',
  `CategoryName` varchar(60) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `UseStat` tinyint(1) NOT NULL default '1',
  `Orders` int(11) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_commend` (
  `ID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `BoardName` varchar(60) NOT NULL default '',
  `PostID` varchar(40) NOT NULL default '',
  `PostMainID` varchar(40) NOT NULL default '',
  `UserID` varchar(40) NOT NULL default '',
  `UserName` varchar(20) NOT NULL default '',
  `CommendBoardID` bigint(20) NOT NULL default '0',
  `CommendTop` tinyint(1) NOT NULL default '0',
  `Title` varchar(150) default NULL,
  `BoardCategory` varchar(40) default NULL,
  `TopCategory` varchar(40) default NULL,
  `CreateTime` bigint(20) NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_config` (
  `ID` varchar(50) NOT NULL default '',
  `ConfContext` text,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_elite` (
  `ID` bigint(20) NOT NULL auto_increment,
  `BoardID` bigint(20) NOT NULL default '0',
  `ParentID` bigint(20) NOT NULL default '0',
  `ParentIDs` text,
  `EliteName` varchar(90) default NULL,
  `CreateUser` varchar(60) default NULL,
  `EliteTime` bigint(20) default '0',
  `Orders` int(11) default '0',
  UNIQUE KEY `ID` (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_forum` (
  `ID` varchar(40) NOT NULL default '',
  `ParentID` varchar(40) NOT NULL default '',
  `MainID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `BoardName` varchar(60) default NULL,
  `ReNum` int(11) default '0',
  `Face` tinyint(2) default '1',
  `UserID` varchar(40) default NULL,
  `UserName` varchar(20) default NULL,
  `NickName` varchar(60) default NULL,
  `Title` varchar(150) default NULL,
  `Detail` text,
  `Sign` text,
  `ArtSize` int(11) default '0',
  `Click` int(11) default '0',
  `PostTime` bigint(20) default '0',
  `LastTime` bigint(20) default '0',
  `IPAddress` varchar(20) default NULL,
  `IsNew` tinyint(1) default '0',
  `Elite` bigint(20) default '0',
  `EliteID` bigint(20) default '0',
  `Agree` int(11) default '0',
  `BeAgainst` int(11) default '0',
  `CanNotDel` tinyint(1) default '0',
  `CanNotRe` tinyint(1) default '0',
  `Commend` bigint(20) default '0',
  `DelSign` tinyint(1) default '0',
  `DelUserID` varchar(40) default NULL,
  `DelUserName` varchar(20) default NULL,
  `DelTime` bigint(20) default '0',
  `DelIP` varchar(20) default NULL,
  `Amend` varchar(255) default NULL,
  `DoEliteName` varchar(20) default '0',
  `DoEliteTime` bigint(20) default '0',
  `HaveAttachFile` tinyint(1) default '0',
  `AttachFileName` text,
  `LastPostUserName` varchar(20) default NULL,
  `LastPostTitle` varchar(150) default NULL,
  `LastPostNickName` varchar(60) default NULL,
  `IsTop` bigint(20) default '0',
  `IsLock` tinyint(1) default '0',
  `Auditing` tinyint(1) default '0',
  `AuditingAttachFile` tinyint(1) default '0',
  `IsVote` tinyint(1) default '0',
  `IsHidden` tinyint(4) default '0',
  `IsHiddenValue` int(11) default '1',
  `EditType` tinyint(1) default '0',
  `QuoteText` text,
  `QuoteEditType` tinyint(1) default '0',
  `PostType` tinyint(1) default '0',
  `TitleColor` tinyint(2) default '0',
  `UserBlog` tinyint(1) default '0',
  `IndexStatus` tinyint(1) default '0',
  `EmailInform` tinyint(1) default '0',
  `MsgInform` tinyint(1) default '0',
  `VoteID` varchar(40) default NULL,
  `TagID` varchar(40) default '0',
  `TagName` varchar(255) default NULL,
  `IsGuest` tinyint(1) default '0',
  `PreviewAttach` tinyint(1) DEFAULT '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `MainID` (`MainID`),
  KEY `BoardID` (`BoardID`),  
  KEY `LastTime` (`LastTime`),
  KEY `PostTime` (`PostTime`),
  KEY `UserID` (`UserID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_forum_history` (
  `ID` varchar(40) NOT NULL default '',
  `ParentID` varchar(40) NOT NULL default '',
  `MainID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `BoardName` varchar(60) default NULL,
  `ReNum` int(11) default '0',
  `Face` tinyint(2) default '1',
  `UserID` varchar(40) default NULL,
  `UserName` varchar(20) default NULL,
  `NickName` varchar(60) default NULL,
  `Title` varchar(150) default NULL,
  `Detail` text,
  `Sign` text,
  `ArtSize` int(11) default '0',
  `Click` int(11) default '0',
  `PostTime` bigint(20) default '0',
  `LastTime` bigint(20) default '0',
  `IPAddress` varchar(20) default NULL,
  `IsNew` tinyint(1) default '0',
  `Elite` bigint(20) default '0',
  `EliteID` bigint(20) default '0',
  `Agree` int(11) default '0',
  `BeAgainst` int(11) default '0',
  `CanNotDel` tinyint(1) default '0',
  `CanNotRe` tinyint(1) default '0',
  `Commend` bigint(20) default '0',
  `DelSign` tinyint(1) default '0',
  `DelUserID` varchar(40) default NULL,
  `DelUserName` varchar(20) default NULL,
  `DelTime` bigint(20) default '0',
  `DelIP` varchar(20) default NULL,
  `Amend` varchar(255) default NULL,
  `DoEliteName` varchar(20) default '0',
  `DoEliteTime` bigint(20) default '0',
  `HaveAttachFile` tinyint(1) default '0',
  `AttachFileName` text,
  `LastPostUserName` varchar(20) default NULL,
  `LastPostTitle` varchar(150) default NULL,
  `LastPostNickName` varchar(60) default NULL,
  `IsTop` bigint(20) default '0',
  `IsLock` tinyint(1) default '0',
  `Auditing` tinyint(1) default '0',
  `AuditingAttachFile` tinyint(1) default '0',
  `IsVote` tinyint(1) default '0',
  `IsHidden` tinyint(4) default '0',
  `IsHiddenValue` int(11) default '1',
  `EditType` tinyint(1) default '0',
  `QuoteText` text,
  `QuoteEditType` tinyint(1) default '0',
  `PostType` tinyint(1) default '0',
  `TitleColor` tinyint(2) default '0',
  `UserBlog` tinyint(1) default '0',
  `IndexStatus` tinyint(1) default '0',
  `EmailInform` tinyint(1) default '0',
  `MsgInform` tinyint(1) default '0',
  `VoteID` varchar(40) default NULL,
  `TagID` varchar(40) default '0',
  `TagName` varchar(255) default NULL,
  `IsGuest` tinyint(1) default '0',
  `PreviewAttach` tinyint(1) DEFAULT '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `MainID` (`MainID`),
  KEY `BoardID` (`BoardID`),  
  KEY `LastTime` (`LastTime`),
  KEY `PostTime` (`PostTime`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_forumarchives_0` (
  `ID` varchar(40) NOT NULL default '',
  `ParentID` varchar(40) NOT NULL default '',
  `MainID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `BoardName` varchar(60) default NULL,
  `ReNum` int(11) default '0',
  `Face` tinyint(2) default '1',
  `UserID` varchar(40) default NULL,
  `UserName` varchar(20) default NULL,
  `NickName` varchar(60) default NULL,
  `Title` varchar(150) default NULL,
  `Detail` text,
  `Sign` text,
  `ArtSize` int(11) default '0',
  `Click` int(11) default '0',
  `PostTime` bigint(20) default '0',
  `LastTime` bigint(20) default '0',
  `IPAddress` varchar(20) default NULL,
  `IsNew` tinyint(1) default '0',
  `Elite` bigint(20) default '0',
  `EliteID` bigint(20) default '0',
  `Agree` int(11) default '0',
  `BeAgainst` int(11) default '0',
  `CanNotDel` tinyint(1) default '0',
  `CanNotRe` tinyint(1) default '0',
  `Commend` bigint(20) default '0',
  `DelSign` tinyint(1) default '0',
  `DelUserID` varchar(40) default NULL,
  `DelUserName` varchar(20) default NULL,
  `DelTime` bigint(20) default '0',
  `DelIP` varchar(20) default NULL,
  `Amend` varchar(255) default NULL,
  `DoEliteName` varchar(20) default '0',
  `DoEliteTime` bigint(20) default '0',
  `HaveAttachFile` tinyint(1) default '0',
  `AttachFileName` text,
  `LastPostUserName` varchar(20) default NULL,
  `LastPostTitle` varchar(150) default NULL,
  `LastPostNickName` varchar(60) default NULL,
  `IsTop` bigint(20) default '0',
  `IsLock` tinyint(1) default '0',
  `Auditing` tinyint(1) default '0',
  `AuditingAttachFile` tinyint(1) default '0',
  `IsVote` tinyint(1) default '0',
  `IsHidden` tinyint(4) default '0',
  `IsHiddenValue` int(11) default '1',
  `EditType` tinyint(1) default '0',
  `QuoteText` text,
  `QuoteEditType` tinyint(1) default '0',
  `PostType` tinyint(1) default '0',
  `TitleColor` tinyint(2) default '0',
  `UserBlog` tinyint(1) default '0',
  `IndexStatus` tinyint(1) default '0',
  `EmailInform` tinyint(1) default '0',
  `MsgInform` tinyint(1) default '0',
  `VoteID` varchar(40) default NULL,
  `TagID` varchar(40) default '0',
  `TagName` varchar(255) default NULL,
  `IsGuest` tinyint(1) default '0',
  `PreviewAttach` tinyint(1) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `MainID` (`MainID`),
  KEY `BoardID` (`BoardID`),
  KEY `LastTime` (`LastTime`),
  KEY `PostTime` (`PostTime`),
  KEY `UserID` (`UserID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_forumarchives_1` (
  `ID` varchar(40) NOT NULL default '',
  `ParentID` varchar(40) NOT NULL default '',
  `MainID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `BoardName` varchar(60) default NULL,
  `ReNum` int(11) default '0',
  `Face` tinyint(2) default '1',
  `UserID` varchar(40) default NULL,
  `UserName` varchar(20) default NULL,
  `NickName` varchar(60) default NULL,
  `Title` varchar(150) default NULL,
  `Detail` text,
  `Sign` text,
  `ArtSize` int(11) default '0',
  `Click` int(11) default '0',
  `PostTime` bigint(20) default '0',
  `LastTime` bigint(20) default '0',
  `IPAddress` varchar(20) default NULL,
  `IsNew` tinyint(1) default '0',
  `Elite` bigint(20) default '0',
  `EliteID` bigint(20) default '0',
  `Agree` int(11) default '0',
  `BeAgainst` int(11) default '0',
  `CanNotDel` tinyint(1) default '0',
  `CanNotRe` tinyint(1) default '0',
  `Commend` bigint(20) default '0',
  `DelSign` tinyint(1) default '0',
  `DelUserID` varchar(40) default NULL,
  `DelUserName` varchar(20) default NULL,
  `DelTime` bigint(20) default '0',
  `DelIP` varchar(20) default NULL,
  `Amend` varchar(255) default NULL,
  `DoEliteName` varchar(20) default '0',
  `DoEliteTime` bigint(20) default '0',
  `HaveAttachFile` tinyint(1) default '0',
  `AttachFileName` text,
  `LastPostUserName` varchar(20) default NULL,
  `LastPostTitle` varchar(150) default NULL,
  `LastPostNickName` varchar(60) default NULL,
  `IsTop` bigint(20) default '0',
  `IsLock` tinyint(1) default '0',
  `Auditing` tinyint(1) default '0',
  `AuditingAttachFile` tinyint(1) default '0',
  `IsVote` tinyint(1) default '0',
  `IsHidden` tinyint(4) default '0',
  `IsHiddenValue` int(11) default '1',
  `EditType` tinyint(1) default '0',
  `QuoteText` text,
  `QuoteEditType` tinyint(1) default '0',
  `PostType` tinyint(1) default '0',
  `TitleColor` tinyint(2) default '0',
  `UserBlog` tinyint(1) default '0',
  `IndexStatus` tinyint(1) default '0',
  `EmailInform` tinyint(1) default '0',
  `MsgInform` tinyint(1) default '0',
  `VoteID` varchar(40) default NULL,
  `TagID` varchar(40) default '0',
  `TagName` varchar(255) default NULL,
  `IsGuest` tinyint(1) default '0',
  `PreviewAttach` tinyint(1) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `MainID` (`MainID`),
  KEY `BoardID` (`BoardID`),
  KEY `LastTime` (`LastTime`),
  KEY `PostTime` (`PostTime`),
  KEY `UserID` (`UserID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_forumarchives_2` (
  `ID` varchar(40) NOT NULL default '',
  `ParentID` varchar(40) NOT NULL default '',
  `MainID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `BoardName` varchar(60) default NULL,
  `ReNum` int(11) default '0',
  `Face` tinyint(2) default '1',
  `UserID` varchar(40) default NULL,
  `UserName` varchar(20) default NULL,
  `NickName` varchar(60) default NULL,
  `Title` varchar(150) default NULL,
  `Detail` text,
  `Sign` text,
  `ArtSize` int(11) default '0',
  `Click` int(11) default '0',
  `PostTime` bigint(20) default '0',
  `LastTime` bigint(20) default '0',
  `IPAddress` varchar(20) default NULL,
  `IsNew` tinyint(1) default '0',
  `Elite` bigint(20) default '0',
  `EliteID` bigint(20) default '0',
  `Agree` int(11) default '0',
  `BeAgainst` int(11) default '0',
  `CanNotDel` tinyint(1) default '0',
  `CanNotRe` tinyint(1) default '0',
  `Commend` bigint(20) default '0',
  `DelSign` tinyint(1) default '0',
  `DelUserID` varchar(40) default NULL,
  `DelUserName` varchar(20) default NULL,
  `DelTime` bigint(20) default '0',
  `DelIP` varchar(20) default NULL,
  `Amend` varchar(255) default NULL,
  `DoEliteName` varchar(20) default '0',
  `DoEliteTime` bigint(20) default '0',
  `HaveAttachFile` tinyint(1) default '0',
  `AttachFileName` text,
  `LastPostUserName` varchar(20) default NULL,
  `LastPostTitle` varchar(150) default NULL,
  `LastPostNickName` varchar(60) default NULL,
  `IsTop` bigint(20) default '0',
  `IsLock` tinyint(1) default '0',
  `Auditing` tinyint(1) default '0',
  `AuditingAttachFile` tinyint(1) default '0',
  `IsVote` tinyint(1) default '0',
  `IsHidden` tinyint(4) default '0',
  `IsHiddenValue` int(11) default '1',
  `EditType` tinyint(1) default '0',
  `QuoteText` text,
  `QuoteEditType` tinyint(1) default '0',
  `PostType` tinyint(1) default '0',
  `TitleColor` tinyint(2) default '0',
  `UserBlog` tinyint(1) default '0',
  `IndexStatus` tinyint(1) default '0',
  `EmailInform` tinyint(1) default '0',
  `MsgInform` tinyint(1) default '0',
  `VoteID` varchar(40) default NULL,
  `TagID` varchar(40) default '0',
  `TagName` varchar(255) default NULL,
  `IsGuest` tinyint(1) default '0',
  `PreviewAttach` tinyint(1) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `MainID` (`MainID`),
  KEY `BoardID` (`BoardID`),
  KEY `LastTime` (`LastTime`),
  KEY `PostTime` (`PostTime`),
  KEY `UserID` (`UserID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_forumarchives_3` (
  `ID` varchar(40) NOT NULL default '',
  `ParentID` varchar(40) NOT NULL default '',
  `MainID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `BoardName` varchar(60) default NULL,
  `ReNum` int(11) default '0',
  `Face` tinyint(2) default '1',
  `UserID` varchar(40) default NULL,
  `UserName` varchar(20) default NULL,
  `NickName` varchar(60) default NULL,
  `Title` varchar(150) default NULL,
  `Detail` text,
  `Sign` text,
  `ArtSize` int(11) default '0',
  `Click` int(11) default '0',
  `PostTime` bigint(20) default '0',
  `LastTime` bigint(20) default '0',
  `IPAddress` varchar(20) default NULL,
  `IsNew` tinyint(1) default '0',
  `Elite` bigint(20) default '0',
  `EliteID` bigint(20) default '0',
  `Agree` int(11) default '0',
  `BeAgainst` int(11) default '0',
  `CanNotDel` tinyint(1) default '0',
  `CanNotRe` tinyint(1) default '0',
  `Commend` bigint(20) default '0',
  `DelSign` tinyint(1) default '0',
  `DelUserID` varchar(40) default NULL,
  `DelUserName` varchar(20) default NULL,
  `DelTime` bigint(20) default '0',
  `DelIP` varchar(20) default NULL,
  `Amend` varchar(255) default NULL,
  `DoEliteName` varchar(20) default '0',
  `DoEliteTime` bigint(20) default '0',
  `HaveAttachFile` tinyint(1) default '0',
  `AttachFileName` text,
  `LastPostUserName` varchar(20) default NULL,
  `LastPostTitle` varchar(150) default NULL,
  `LastPostNickName` varchar(60) default NULL,
  `IsTop` bigint(20) default '0',
  `IsLock` tinyint(1) default '0',
  `Auditing` tinyint(1) default '0',
  `AuditingAttachFile` tinyint(1) default '0',
  `IsVote` tinyint(1) default '0',
  `IsHidden` tinyint(4) default '0',
  `IsHiddenValue` int(11) default '1',
  `EditType` tinyint(1) default '0',
  `QuoteText` text,
  `QuoteEditType` tinyint(1) default '0',
  `PostType` tinyint(1) default '0',
  `TitleColor` tinyint(2) default '0',
  `UserBlog` tinyint(1) default '0',
  `IndexStatus` tinyint(1) default '0',
  `EmailInform` tinyint(1) default '0',
  `MsgInform` tinyint(1) default '0',
  `VoteID` varchar(40) default NULL,
  `TagID` varchar(40) default '0',
  `TagName` varchar(255) default NULL,
  `IsGuest` tinyint(1) default '0',
  `PreviewAttach` tinyint(1) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `MainID` (`MainID`),
  KEY `BoardID` (`BoardID`),
  KEY `LastTime` (`LastTime`),
  KEY `PostTime` (`PostTime`),
  KEY `UserID` (`UserID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_forumarchives_4` (
  `ID` varchar(40) NOT NULL default '',
  `ParentID` varchar(40) NOT NULL default '',
  `MainID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `BoardName` varchar(60) default NULL,
  `ReNum` int(11) default '0',
  `Face` tinyint(2) default '1',
  `UserID` varchar(40) default NULL,
  `UserName` varchar(20) default NULL,
  `NickName` varchar(60) default NULL,
  `Title` varchar(150) default NULL,
  `Detail` text,
  `Sign` text,
  `ArtSize` int(11) default '0',
  `Click` int(11) default '0',
  `PostTime` bigint(20) default '0',
  `LastTime` bigint(20) default '0',
  `IPAddress` varchar(20) default NULL,
  `IsNew` tinyint(1) default '0',
  `Elite` bigint(20) default '0',
  `EliteID` bigint(20) default '0',
  `Agree` int(11) default '0',
  `BeAgainst` int(11) default '0',
  `CanNotDel` tinyint(1) default '0',
  `CanNotRe` tinyint(1) default '0',
  `Commend` bigint(20) default '0',
  `DelSign` tinyint(1) default '0',
  `DelUserID` varchar(40) default NULL,
  `DelUserName` varchar(20) default NULL,
  `DelTime` bigint(20) default '0',
  `DelIP` varchar(20) default NULL,
  `Amend` varchar(255) default NULL,
  `DoEliteName` varchar(20) default '0',
  `DoEliteTime` bigint(20) default '0',
  `HaveAttachFile` tinyint(1) default '0',
  `AttachFileName` text,
  `LastPostUserName` varchar(20) default NULL,
  `LastPostTitle` varchar(150) default NULL,
  `LastPostNickName` varchar(60) default NULL,
  `IsTop` bigint(20) default '0',
  `IsLock` tinyint(1) default '0',
  `Auditing` tinyint(1) default '0',
  `AuditingAttachFile` tinyint(1) default '0',
  `IsVote` tinyint(1) default '0',
  `IsHidden` tinyint(4) default '0',
  `IsHiddenValue` int(11) default '1',
  `EditType` tinyint(1) default '0',
  `QuoteText` text,
  `QuoteEditType` tinyint(1) default '0',
  `PostType` tinyint(1) default '0',
  `TitleColor` tinyint(2) default '0',
  `UserBlog` tinyint(1) default '0',
  `IndexStatus` tinyint(1) default '0',
  `EmailInform` tinyint(1) default '0',
  `MsgInform` tinyint(1) default '0',
  `VoteID` varchar(40) default NULL,
  `TagID` varchar(40) default '0',
  `TagName` varchar(255) default NULL,
  `IsGuest` tinyint(1) default '0',
  `PreviewAttach` tinyint(1) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `MainID` (`MainID`),
  KEY `BoardID` (`BoardID`),
  KEY `LastTime` (`LastTime`),
  KEY `PostTime` (`PostTime`),
  KEY `UserID` (`UserID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_forumarchives_5` (
  `ID` varchar(40) NOT NULL default '',
  `ParentID` varchar(40) NOT NULL default '',
  `MainID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `BoardName` varchar(60) default NULL,
  `ReNum` int(11) default '0',
  `Face` tinyint(2) default '1',
  `UserID` varchar(40) default NULL,
  `UserName` varchar(20) default NULL,
  `NickName` varchar(60) default NULL,
  `Title` varchar(150) default NULL,
  `Detail` text,
  `Sign` text,
  `ArtSize` int(11) default '0',
  `Click` int(11) default '0',
  `PostTime` bigint(20) default '0',
  `LastTime` bigint(20) default '0',
  `IPAddress` varchar(20) default NULL,
  `IsNew` tinyint(1) default '0',
  `Elite` bigint(20) default '0',
  `EliteID` bigint(20) default '0',
  `Agree` int(11) default '0',
  `BeAgainst` int(11) default '0',
  `CanNotDel` tinyint(1) default '0',
  `CanNotRe` tinyint(1) default '0',
  `Commend` bigint(20) default '0',
  `DelSign` tinyint(1) default '0',
  `DelUserID` varchar(40) default NULL,
  `DelUserName` varchar(20) default NULL,
  `DelTime` bigint(20) default '0',
  `DelIP` varchar(20) default NULL,
  `Amend` varchar(255) default NULL,
  `DoEliteName` varchar(20) default '0',
  `DoEliteTime` bigint(20) default '0',
  `HaveAttachFile` tinyint(1) default '0',
  `AttachFileName` text,
  `LastPostUserName` varchar(20) default NULL,
  `LastPostTitle` varchar(150) default NULL,
  `LastPostNickName` varchar(60) default NULL,
  `IsTop` bigint(20) default '0',
  `IsLock` tinyint(1) default '0',
  `Auditing` tinyint(1) default '0',
  `AuditingAttachFile` tinyint(1) default '0',
  `IsVote` tinyint(1) default '0',
  `IsHidden` tinyint(4) default '0',
  `IsHiddenValue` int(11) default '1',
  `EditType` tinyint(1) default '0',
  `QuoteText` text,
  `QuoteEditType` tinyint(1) default '0',
  `PostType` tinyint(1) default '0',
  `TitleColor` tinyint(2) default '0',
  `UserBlog` tinyint(1) default '0',
  `IndexStatus` tinyint(1) default '0',
  `EmailInform` tinyint(1) default '0',
  `MsgInform` tinyint(1) default '0',
  `VoteID` varchar(40) default NULL,
  `TagID` varchar(40) default '0',
  `TagName` varchar(255) default NULL,
  `IsGuest` tinyint(1) default '0',
  `PreviewAttach` tinyint(1) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `MainID` (`MainID`),
  KEY `BoardID` (`BoardID`),
  KEY `LastTime` (`LastTime`),
  KEY `PostTime` (`PostTime`),
  KEY `UserID` (`UserID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_forumarchives_6` (
  `ID` varchar(40) NOT NULL default '',
  `ParentID` varchar(40) NOT NULL default '',
  `MainID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `BoardName` varchar(60) default NULL,
  `ReNum` int(11) default '0',
  `Face` tinyint(2) default '1',
  `UserID` varchar(40) default NULL,
  `UserName` varchar(20) default NULL,
  `NickName` varchar(60) default NULL,
  `Title` varchar(150) default NULL,
  `Detail` text,
  `Sign` text,
  `ArtSize` int(11) default '0',
  `Click` int(11) default '0',
  `PostTime` bigint(20) default '0',
  `LastTime` bigint(20) default '0',
  `IPAddress` varchar(20) default NULL,
  `IsNew` tinyint(1) default '0',
  `Elite` bigint(20) default '0',
  `EliteID` bigint(20) default '0',
  `Agree` int(11) default '0',
  `BeAgainst` int(11) default '0',
  `CanNotDel` tinyint(1) default '0',
  `CanNotRe` tinyint(1) default '0',
  `Commend` bigint(20) default '0',
  `DelSign` tinyint(1) default '0',
  `DelUserID` varchar(40) default NULL,
  `DelUserName` varchar(20) default NULL,
  `DelTime` bigint(20) default '0',
  `DelIP` varchar(20) default NULL,
  `Amend` varchar(255) default NULL,
  `DoEliteName` varchar(20) default '0',
  `DoEliteTime` bigint(20) default '0',
  `HaveAttachFile` tinyint(1) default '0',
  `AttachFileName` text,
  `LastPostUserName` varchar(20) default NULL,
  `LastPostTitle` varchar(150) default NULL,
  `LastPostNickName` varchar(60) default NULL,
  `IsTop` bigint(20) default '0',
  `IsLock` tinyint(1) default '0',
  `Auditing` tinyint(1) default '0',
  `AuditingAttachFile` tinyint(1) default '0',
  `IsVote` tinyint(1) default '0',
  `IsHidden` tinyint(4) default '0',
  `IsHiddenValue` int(11) default '1',
  `EditType` tinyint(1) default '0',
  `QuoteText` text,
  `QuoteEditType` tinyint(1) default '0',
  `PostType` tinyint(1) default '0',
  `TitleColor` tinyint(2) default '0',
  `UserBlog` tinyint(1) default '0',
  `IndexStatus` tinyint(1) default '0',
  `EmailInform` tinyint(1) default '0',
  `MsgInform` tinyint(1) default '0',
  `VoteID` varchar(40) default NULL,
  `TagID` varchar(40) default '0',
  `TagName` varchar(255) default NULL,
  `IsGuest` tinyint(1) default '0',
  `PreviewAttach` tinyint(1) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `MainID` (`MainID`),
  KEY `BoardID` (`BoardID`),
  KEY `LastTime` (`LastTime`),
  KEY `PostTime` (`PostTime`),
  KEY `UserID` (`UserID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_forumarchives_7` (
  `ID` varchar(40) NOT NULL default '',
  `ParentID` varchar(40) NOT NULL default '',
  `MainID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `BoardName` varchar(60) default NULL,
  `ReNum` int(11) default '0',
  `Face` tinyint(2) default '1',
  `UserID` varchar(40) default NULL,
  `UserName` varchar(20) default NULL,
  `NickName` varchar(60) default NULL,
  `Title` varchar(150) default NULL,
  `Detail` text,
  `Sign` text,
  `ArtSize` int(11) default '0',
  `Click` int(11) default '0',
  `PostTime` bigint(20) default '0',
  `LastTime` bigint(20) default '0',
  `IPAddress` varchar(20) default NULL,
  `IsNew` tinyint(1) default '0',
  `Elite` bigint(20) default '0',
  `EliteID` bigint(20) default '0',
  `Agree` int(11) default '0',
  `BeAgainst` int(11) default '0',
  `CanNotDel` tinyint(1) default '0',
  `CanNotRe` tinyint(1) default '0',
  `Commend` bigint(20) default '0',
  `DelSign` tinyint(1) default '0',
  `DelUserID` varchar(40) default NULL,
  `DelUserName` varchar(20) default NULL,
  `DelTime` bigint(20) default '0',
  `DelIP` varchar(20) default NULL,
  `Amend` varchar(255) default NULL,
  `DoEliteName` varchar(20) default '0',
  `DoEliteTime` bigint(20) default '0',
  `HaveAttachFile` tinyint(1) default '0',
  `AttachFileName` text,
  `LastPostUserName` varchar(20) default NULL,
  `LastPostTitle` varchar(150) default NULL,
  `LastPostNickName` varchar(60) default NULL,
  `IsTop` bigint(20) default '0',
  `IsLock` tinyint(1) default '0',
  `Auditing` tinyint(1) default '0',
  `AuditingAttachFile` tinyint(1) default '0',
  `IsVote` tinyint(1) default '0',
  `IsHidden` tinyint(4) default '0',
  `IsHiddenValue` int(11) default '1',
  `EditType` tinyint(1) default '0',
  `QuoteText` text,
  `QuoteEditType` tinyint(1) default '0',
  `PostType` tinyint(1) default '0',
  `TitleColor` tinyint(2) default '0',
  `UserBlog` tinyint(1) default '0',
  `IndexStatus` tinyint(1) default '0',
  `EmailInform` tinyint(1) default '0',
  `MsgInform` tinyint(1) default '0',
  `VoteID` varchar(40) default NULL,
  `TagID` varchar(40) default '0',
  `TagName` varchar(255) default NULL,
  `IsGuest` tinyint(1) default '0',
  `PreviewAttach` tinyint(1) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `MainID` (`MainID`),
  KEY `BoardID` (`BoardID`),
  KEY `LastTime` (`LastTime`),
  KEY `PostTime` (`PostTime`),
  KEY `UserID` (`UserID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_forumarchives_8` (
  `ID` varchar(40) NOT NULL default '',
  `ParentID` varchar(40) NOT NULL default '',
  `MainID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `BoardName` varchar(60) default NULL,
  `ReNum` int(11) default '0',
  `Face` tinyint(2) default '1',
  `UserID` varchar(40) default NULL,
  `UserName` varchar(20) default NULL,
  `NickName` varchar(60) default NULL,
  `Title` varchar(150) default NULL,
  `Detail` text,
  `Sign` text,
  `ArtSize` int(11) default '0',
  `Click` int(11) default '0',
  `PostTime` bigint(20) default '0',
  `LastTime` bigint(20) default '0',
  `IPAddress` varchar(20) default NULL,
  `IsNew` tinyint(1) default '0',
  `Elite` bigint(20) default '0',
  `EliteID` bigint(20) default '0',
  `Agree` int(11) default '0',
  `BeAgainst` int(11) default '0',
  `CanNotDel` tinyint(1) default '0',
  `CanNotRe` tinyint(1) default '0',
  `Commend` bigint(20) default '0',
  `DelSign` tinyint(1) default '0',
  `DelUserID` varchar(40) default NULL,
  `DelUserName` varchar(20) default NULL,
  `DelTime` bigint(20) default '0',
  `DelIP` varchar(20) default NULL,
  `Amend` varchar(255) default NULL,
  `DoEliteName` varchar(20) default '0',
  `DoEliteTime` bigint(20) default '0',
  `HaveAttachFile` tinyint(1) default '0',
  `AttachFileName` text,
  `LastPostUserName` varchar(20) default NULL,
  `LastPostTitle` varchar(150) default NULL,
  `LastPostNickName` varchar(60) default NULL,
  `IsTop` bigint(20) default '0',
  `IsLock` tinyint(1) default '0',
  `Auditing` tinyint(1) default '0',
  `AuditingAttachFile` tinyint(1) default '0',
  `IsVote` tinyint(1) default '0',
  `IsHidden` tinyint(4) default '0',
  `IsHiddenValue` int(11) default '1',
  `EditType` tinyint(1) default '0',
  `QuoteText` text,
  `QuoteEditType` tinyint(1) default '0',
  `PostType` tinyint(1) default '0',
  `TitleColor` tinyint(2) default '0',
  `UserBlog` tinyint(1) default '0',
  `IndexStatus` tinyint(1) default '0',
  `EmailInform` tinyint(1) default '0',
  `MsgInform` tinyint(1) default '0',
  `VoteID` varchar(40) default NULL,
  `TagID` varchar(40) default '0',
  `TagName` varchar(255) default NULL,
  `IsGuest` tinyint(1) default '0',
  `PreviewAttach` tinyint(1) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `MainID` (`MainID`),
  KEY `BoardID` (`BoardID`),
  KEY `LastTime` (`LastTime`),
  KEY `PostTime` (`PostTime`),
  KEY `UserID` (`UserID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_forumarchives_9` (
  `ID` varchar(40) NOT NULL default '',
  `ParentID` varchar(40) NOT NULL default '',
  `MainID` varchar(40) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `BoardName` varchar(60) default NULL,
  `ReNum` int(11) default '0',
  `Face` tinyint(2) default '1',
  `UserID` varchar(40) default NULL,
  `UserName` varchar(20) default NULL,
  `NickName` varchar(60) default NULL,
  `Title` varchar(150) default NULL,
  `Detail` text,
  `Sign` text,
  `ArtSize` int(11) default '0',
  `Click` int(11) default '0',
  `PostTime` bigint(20) default '0',
  `LastTime` bigint(20) default '0',
  `IPAddress` varchar(20) default NULL,
  `IsNew` tinyint(1) default '0',
  `Elite` bigint(20) default '0',
  `EliteID` bigint(20) default '0',
  `Agree` int(11) default '0',
  `BeAgainst` int(11) default '0',
  `CanNotDel` tinyint(1) default '0',
  `CanNotRe` tinyint(1) default '0',
  `Commend` bigint(20) default '0',
  `DelSign` tinyint(1) default '0',
  `DelUserID` varchar(40) default NULL,
  `DelUserName` varchar(20) default NULL,
  `DelTime` bigint(20) default '0',
  `DelIP` varchar(20) default NULL,
  `Amend` varchar(255) default NULL,
  `DoEliteName` varchar(20) default '0',
  `DoEliteTime` bigint(20) default '0',
  `HaveAttachFile` tinyint(1) default '0',
  `AttachFileName` text,
  `LastPostUserName` varchar(20) default NULL,
  `LastPostTitle` varchar(150) default NULL,
  `LastPostNickName` varchar(60) default NULL,
  `IsTop` bigint(20) default '0',
  `IsLock` tinyint(1) default '0',
  `Auditing` tinyint(1) default '0',
  `AuditingAttachFile` tinyint(1) default '0',
  `IsVote` tinyint(1) default '0',
  `IsHidden` tinyint(4) default '0',
  `IsHiddenValue` int(11) default '1',
  `EditType` tinyint(1) default '0',
  `QuoteText` text,
  `QuoteEditType` tinyint(1) default '0',
  `PostType` tinyint(1) default '0',
  `TitleColor` tinyint(2) default '0',
  `UserBlog` tinyint(1) default '0',
  `IndexStatus` tinyint(1) default '0',
  `EmailInform` tinyint(1) default '0',
  `MsgInform` tinyint(1) default '0',
  `VoteID` varchar(40) default NULL,
  `TagID` varchar(40) default '0',
  `TagName` varchar(255) default NULL,
  `IsGuest` tinyint(1) default '0',
  `PreviewAttach` tinyint(1) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `MainID` (`MainID`),
  KEY `BoardID` (`BoardID`),
  KEY `LastTime` (`LastTime`),
  KEY `PostTime` (`PostTime`),
  KEY `UserID` (`UserID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_forumbuy` (
  `ID` varchar(40) NOT NULL,
  `PostID` varchar(40) NOT NULL,
  `BuyFromID` varchar(40) NOT NULL,
  `BuyFromName` varchar(20) NOT NULL,
  `BuyToID` varchar(40) NOT NULL,
  `BuyToName` varchar(20) NOT NULL,
  `BuyPrice` int(11) NOT NULL default '0',
  `BuyToUserIncome` int(11) NOT NULL default '0',
  `BuyTime` bigint(20) NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_friend` (
  `ID` varchar(40) NOT NULL default '',
  `UserID` varchar(40) NOT NULL default '',
  `UserName` varchar(20) NOT NULL default '',
  `FriendID` varchar(40) NOT NULL default '',
  `FriendName` varchar(20) NOT NULL default '',
  `FriendComment` text,
  `IsBlack` tinyint(1) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `UserID` (`UserID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_grouprole` (
  `GroupID` int(11) NOT NULL default '0',
  `RoleID` int(11) NOT NULL default '0',
  PRIMARY KEY  (`GroupID`,`RoleID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_loginerror` (
  `ID` varchar(40) NOT NULL default '',
  `UserID` varchar(40) NOT NULL default '',
  `ErrorTimes` int(11) NOT NULL default '0',
  `LoginTime` bigint(20) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  UNIQUE KEY `UserID` (`UserID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_note` (
  `ID` varchar(40) NOT NULL default '',
  `FromID` varchar(40) NOT NULL default '',
  `FromUserName` varchar(20) NOT NULL default '',
  `FromNickName` varchar(60) NOT NULL default '',
  `ToID` varchar(40) NOT NULL default '',
  `ToUserName` varchar(20) NOT NULL default '',
  `ToNickName` varchar(60) NOT NULL default '',
  `NoteType` tinyint(1) NOT NULL default '0',
  `NoteTitle` varchar(150) NOT NULL default '',
  `NoteContext` text NOT NULL,
  `CreateTime` datetime NOT NULL default '0000-00-00 00:00:00',
  `IsNew` tinyint(1) default '1',
  `NeedRe` tinyint(1) default '0',
  `IsRe` tinyint(1) default '0',
  `SysMsg` tinyint(1) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `FromID` (`FromID`),
  KEY `ToID` (`ToID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_permission` (
  `ID` bigint(20) NOT NULL default '0',
  `PermissionName` varchar(255) NOT NULL default '',
  `PermissionResource` varchar(255) default NULL,
  `Action` varchar(255) default NULL,
  `TypeID` int(2) NOT NULL default '0',
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_role` (
  `ID` int(11) NOT NULL auto_increment,
  `RoleName` varchar(255) NOT NULL default '',
  `TypeID` int(2) NOT NULL default '0',
  `Permissions` text,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_subscibe` (
  `ID` varchar(40) NOT NULL default '',
  `UserID` varchar(40) NOT NULL default '',
  `UserName` varchar(20) NOT NULL default '',
  `NickName` varchar(60) NOT NULL default '',
  `PostID` varchar(40) NOT NULL default '',
  `PostTitle` varchar(150) NOT NULL default '',
  `BoardID` bigint(20) NOT NULL default '0',
  `Emailinform` tinyint(1) default '1',
  `Msginform` tinyint(1) default '1',
  `UserEmail` varchar(255) default NULL,
  `CreateTime` datetime default NULL,
  `UserLocale` varchar(20) default 'zh_CN',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_sysnumstat` (
  `ID` varchar(40) NOT NULL,
  `RecDate` varchar(20) NOT NULL,
  `Num0` int(11) default '0',
  `NumInc0` int(11) NOT NULL default '0',
  `Num1` int(11) NOT NULL default '0',
  `NumInc1` int(11) NOT NULL default '0',
  `Num2` int(11) NOT NULL default '0',
  `NumInc2` int(11) NOT NULL default '0',
  `Num3` int(11) NOT NULL default '0',
  `NumInc3` int(11) NOT NULL default '0',
  `Num4` int(11) NOT NULL default '0',
  `NumInc4` int(11) NOT NULL default '0',
  `Num5` int(11) NOT NULL default '0',
  `NumInc5` int(11) NOT NULL default '0',
  `CreateTime` bigint(20) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_userinfo` (
  `ID` varchar(40) NOT NULL default '',
  `UserName` varchar(20) NOT NULL default '',
  `NickName` varchar(60) NOT NULL default '',
  `Passwd` varchar(40) NOT NULL default '',
  `RePasswd` varchar(40) NOT NULL default '',
  `Email` varchar(255) NOT NULL default '',
  `Question` varchar(255) NOT NULL default '',
  `Answer` varchar(255) NOT NULL default '',
  `RegTime` datetime NOT NULL default '0000-00-00 00:00:00',
  `LoginTime` datetime NOT NULL default '0000-00-00 00:00:00',
  `LoginIP` varchar(20) NOT NULL default '',
  `LoginTimes` int(11) NOT NULL default '0',
  `LastLoginTime` datetime default NULL,
  `LastLoginIP` varchar(20) default NULL,
  `ArticleNum` int(11) default '0',
  `StayTime` bigint(20) default '0',
  `ArticleEliteNum` int(11) default '0',
  `LifeForce` int(11) default '0',
  `UserTitle` tinyint(3) default '0',
  `Coin` int(11) default '0',
  `Literary` int(11) default '0',
  `Experience` int(11) default '0',
  `UserKnow` int(11) default '0',
  `SignName0` varchar(30) default NULL,
  `SignDetail0` text,
  `SignName1` varchar(30) default NULL,
  `SignDetail1` text,
  `SignName2` varchar(30) default NULL,
  `SignDetail2` text,
  `HavePic` tinyint(3) default '0',
  `PicFileName` varchar(255) default NULL,
  `ForumPerNum` tinyint(3) default '20',
  `PostPerNum` tinyint(3) default '10',
  `UserFrom` varchar(255) default NULL,
  `TimeZone` varchar(20) default 'GMT+08:00',
  `BirthYear` int(4) default '1980',
  `BirthMonth` tinyint(2) default '1',
  `BirthDay` tinyint(2) default '1',
  `ReceiveNote` tinyint(1) default '1',
  `AcceptFriend` tinyint(1) default '1',
  `ForumViewMode` tinyint(1) default '0',
  `Validated` tinyint(1) default '1',
  `GroupID` int(11) default '0',
  `HiddenLogin` tinyint(1) default '0',
  `EditType` tinyint(1) default '-1',
  `UserLocale` varchar(20) default 'zh_CN',
  `ValidateCode` varchar(20) default NULL,
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `UserName` (`UserName`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_userdetail` (
  `ID` varchar(40) NOT NULL default '',
  `Height` varchar(255) default NULL,
  `Weight` varchar(255) default NULL,
  `Interest` varchar(255) default NULL,
  `Graduate` varchar(255) default NULL,
  `FavourPeople` varchar(255) default NULL,
  `DreamJob` varchar(255) default NULL,
  `FavourArt` varchar(255) default NULL,
  `FavourMusic` varchar(255) default NULL,
  `FavourPlace` varchar(255) default NULL,
  `FavourMovie` varchar(255) default NULL,
  `FavourChat` varchar(255) default NULL,
  `FavourBook` varchar(255) default NULL,
  `DreamLover` varchar(255) default NULL,
  `FavourTeam` varchar(255) default NULL,
  `HomePage` varchar(255) default '',
  `OicqNo` varchar(255) default '',
  `IcqNo` varchar(255) default '',
  `MSN` varchar(255) default NULL,
  `Yahoo` varchar(255) default NULL,
  `Sex` tinyint(1) default '0',
  `Brief` text,
  PRIMARY KEY  (`ID`),
  CONSTRAINT `FK_USERDETAIL_ID` FOREIGN KEY (`ID`) REFERENCES `bbscs_userinfo` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_usergroup` (
  `ID` int(11) NOT NULL auto_increment,
  `GroupName` varchar(255) NOT NULL default '',
  `GroupDesc` varchar(255) default NULL,
  `TypeID` int(2) NOT NULL default '0',
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_userlevel` (
  `ID` varchar(40) NOT NULL,
  `LevelName` varchar(60) NOT NULL,
  `LevelValue` int(11) NOT NULL default '0',
  `LevelType` tinyint(1) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_useronline` (
  `ID` varchar(40) NOT NULL default '',
  `UserID` varchar(40) NOT NULL default '',
  `UserName` varchar(20) NOT NULL default '',
  `NickName` varchar(60) NOT NULL default '',
  `OnlineTime` bigint(20) default NULL,
  `BoardID` bigint(20) default '0',
  `AtPlace` varchar(255) default NULL,
  `UserGroupID` int(11) default NULL,
  `ValidateCode` varchar(100) default NULL,
  `HiddenUser` tinyint(1) default '0',
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_usertop` (
  `ID` varchar(40) NOT NULL,
  `UserID` varchar(40) NOT NULL,
  `UserName` varchar(20) NOT NULL,
  `NickName` varchar(60) NOT NULL,
  `ValueType` tinyint(2) NOT NULL default '0',
  `UserValue` int(11) default '0',
  `ValueInc` int(11) default NULL,
  PRIMARY KEY  (`ID`),
  KEY `ValueType` (`ValueType`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_vote` (
  `ID` varchar(40) NOT NULL default '',
  `Title` varchar(255) NOT NULL default '',
  `IsM` tinyint(1) default '0',
  `DeadLine` bigint(20) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `id` (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_voteitem` (
  `ID` varchar(40) NOT NULL default '',
  `VoteID` varchar(40) NOT NULL default '',
  `Item` varchar(255) NOT NULL default '',
  `ItemValue` int(11) default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `id` (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
######
CREATE TABLE `bbscs_voteuser` (
  `ID` varchar(40) NOT NULL default '',
  `VoteID` varchar(40) NOT NULL default '',
  `VoteUserID` varchar(40) NOT NULL default '',
  `VoteTime` bigint(20) NOT NULL default '0',
  PRIMARY KEY  (`ID`),
  UNIQUE KEY `id` (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;